export const tagTypes: Record<string, string> = {
  auth: "auth",
  user: "users",
  employees: "employees",
  divisions: "divisions",
  districts: "districts",
  upzelas: "upzelas",
  orders: "orders",
  addresses: "addresses",
  wishlists: "wishlists",
  products: "products",
  carts: "carts",
  product_categories: "product-categories",
  video_gallery_categories: "video_gallery_categories",
  video_gallaries: "video-gallaries",
  blog_category: "blog-category",
  blog: "blog",
  blog_details: "blog-details",
  testimonials: "testimonials",
  question_answers: "question-answers",
  menu: "menu",
  roles: "roles",
  hero: "hero",
  sustainability: "sustainability",
  destinations: "destinations",
  about: "about",
  about_explore: "about-explore",
  about_stats: "about-stats",
  education: "education",
  services: "services",
  gallery: "gallery",
  client_video_reviews: "client-video-reviews",
  chambers: "chambers",
  appointments: "appointments",
  prescriptions: "prescriptions",
  chief_complaints: "chief-complaints",
};

export const tagTypesList: string[] = [
  tagTypes.auth,
  tagTypes.user,
  tagTypes.employees,
  tagTypes.divisions,
  tagTypes.districts,
  tagTypes.upzelas,
  tagTypes.orders,
  tagTypes.addresses,
  tagTypes.wishlists,
  tagTypes.products,
  tagTypes.carts,
  tagTypes.product_categories,
  tagTypes.video_gallery_categories,
  tagTypes.video_gallaries,
  tagTypes.blog_category,
  tagTypes.blog,
  tagTypes.blog_details,
  tagTypes.testimonials,
  tagTypes.question_answers,
  tagTypes.menu,
  tagTypes.roles,
  tagTypes.hero,
  tagTypes.sustainability,
  tagTypes.destinations,
  tagTypes.about,
  tagTypes.about_explore,
  tagTypes.about_stats,
  tagTypes.education,
  tagTypes.services,
  tagTypes.gallery,
  tagTypes.client_video_reviews,
  tagTypes.chambers,
  tagTypes.appointments,
  tagTypes.prescriptions,
  tagTypes.chief_complaints,
];
